/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353434",
        "tertiary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "surface-bright": "#3a3939",
        "secondary": "#ffffff",
        "on-tertiary": "#2f3131",
        "inverse-on-surface": "#313030",
        "on-surface-variant": "#c4c7c8",
        "outline": "#8e9192",
        "tertiary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#5d5f5f",
        "surface": "#141313",
        "accent-cyan": "#00F0FF",
        "on-primary-fixed-variant": "#454747",
        "surface-container": "#201f1f",
        "on-secondary-container": "#bab8b7",
        "surface-dim": "#141313",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary": "#2f3131",
        "on-error-container": "#ffdad6",
        "on-secondary": "#313030",
        "surface-tint": "#c6c6c7",
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#1a1c1c",
        "outline-variant": "#444748",
        "primary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-container": "#636565",
        "primary-fixed": "#e2e2e2",
        "surface-container-highest": "#353434",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-high": "#2a2a2a",
        "surface-base": "#0A0A0A",
        "background": "#000000",
        "on-background": "#e5e2e1",
        "surface-elevated": "#1C1C1E",
        "primary-container": "#e2e2e2",
        "error-container": "#93000a",
        "border-muted": "#2C2C2E",
        "secondary-container": "#4a4949",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "primary-fixed-dim": "#c6c6c7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        unit: "4px",
        "margin-desktop": "64px",
        md: "16px",
        lg: "24px",
        sm: "8px",
        xs: "4px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "display-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
