/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#eff4ff",
        "primary": "#4648d4",
        "inverse-primary": "#c0c1ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#07006c",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#464554",
        "secondary-container": "#dae2fd",
        "surface-tint": "#494bd6",
        "outline-variant": "#c7c4d7",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed": "#e1e0ff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "on-surface": "#0b1c30",
        "primary-container": "#6063ee",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "secondary": "#565e74",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "outline": "#767586",
        "tertiary-container": "#00885d",
        "on-tertiary-fixed-variant": "#005236",
        "surface-dim": "#cbdbf5",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#000703",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#fffbff",
        "tertiary": "#006c49",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        lg: "24px",
        sm: "8px",
        xs: "4px",
        "container-padding": "40px",
        gutter: "24px",
        base: "4px",
        xl: "32px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "1.5", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
